services: 
  not-portfolio:
    container_name: not-portfolio
    build: ./not-portfolio
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    ports:
      - 3000:3000
    secrets:
      - studylog_link
      - comic_comet_link
    volumes:
      - ./not-portfolio:/usr/src/app
